name = "TensorNetworkQuantumSimulator"
uuid = "4de3b72a-362e-43dd-83ff-3f381eda9f9c"
authors = ["JoeyT1994 <jtindall@flatironinstitute.org>", "MSRudolph <manuel.rudolph@web.de>"]
version = "0.0.1"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
DataGraphs = "b5a273c3-7e6c-41f6-98bd-8d7f1525a36a"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
EinExprs = "b1794770-133b-4de1-afb4-526377e9f4c5"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensorNetworks = "2919e153-833c-4bdc-8836-1ea460a35fc7"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
NamedGraphs = "678767b0-92e7-4007-89e4-4527a8725b19"
PEPSKit = "52969e89-939e-4361-9b68-9bc7cde4bdeb"
PauliPropagation = "293282d5-3c99-4fb6-92d0-fd3280a19750"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SimpleGraphAlgorithms = "41400c72-0c58-5c16-8579-4ecbce768449"
SimpleGraphConverter = "205b04f2-f585-4877-a239-566270b3f673"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
TypeParameterAccessors = "7e5a90cf-f82e-492e-a09b-e3e26432c138"

[compat]
Adapt = "4.3.0"
DataGraphs = "0.2.9"
CSV = "0.10.15"
Combinatorics = "1.0.3"
Dictionaries = "0.4"
EinExprs = "0.6.4"
GraphRecipes = "0.5.13"
Graphs = "1.8.0"
ITensorMPS = "0.3.17"
ITensorNetworks = "0.14.2"
ITensors = "0.9"
Interpolations = "0.15.1"
JLD2 = "0.5.15"
JSON = "0.21.4"
KrylovKit = "0.10.1"
LinearAlgebra = "1.11.0"
MKL = "0.9.0"
NPZ = "0.4.3"
NamedGraphs = "0.7"
PEPSKit = "0.6.1"
PauliPropagation = "0.3.0"
QuadGK = "2.11.2"
Revise = "3.8.0"
SimpleGraphAlgorithms = "0.6.0"
SimpleGraphConverter = "0.1.0"
SplitApplyCombine = "1.2.3"
Statistics = "1.11.1"
StatsBase = "0.34.4"
Tables = "1.12.1"
TensorKit = "0.14.11"
TensorOperations = "5.2"
TypeParameterAccessors = "0.3.10"
